# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='down_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='up_count',
        ),
        migrations.AddField(
            model_name='article',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_nums',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
